"""Quellendaten für GEDCOM-Export."""

# Strukturierte Quellenangaben für GEDCOM SOUR-Einträge
SOURCES_DATA = {
    "S1": {
        "titl": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1798-1831 Gb Hb Sb 1613-1798 (unsortiert) Ortsregister (nach Hauptstädten) Gb, Hb, Sb 1564-1831",
        "abbr": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1798-1831",
        "auth": "Mikrofilme aufgenommen von Manuskripten im Historischen Archiv der Stadt Wetzlar.",
        "publ": "FamilySearch; Film 1599946; Aufnahmengruppen-Nummer (DGS) 102779709",
        "repo": "REPO2",
    },
    "S2": {
        "titl": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1564-1611",
        "abbr": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1564-1611",
        "auth": "Mikrofilme aufgenommen von Manuskripten im Historischen Archiv der Stadt Wetzlar.",
        "publ": "FamilySearch; Film 1599704; Aufnahmengruppen-Nummer (DGS) 102779699",
        "repo": "REPO2",
    },
    "S3": {
        "titl": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1611-1632",
        "abbr": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1611-1632",
        "auth": "Mikrofilme aufgenommen von Manuskripten im Historischen Archiv der Stadt Wetzlar.",
        "publ": "FamilySearch; Film 1599705; Aufnahmengruppen-Nummer (DGS) 102779700",
        "repo": "REPO2",
    },
    "S4": {
        "titl": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1633-1670",
        "abbr": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1633-1670",
        "auth": "Mikrofilme aufgenommen von Manuskripten im Historischen Archiv der Stadt Wetzlar.",
        "publ": "FamilySearch; Film 1599706; Aufnahmengruppen-Nummer (DGS) 102779701",
        "repo": "REPO2",
    },
    "S5": {
        "titl": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1671-1695",
        "abbr": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1671-1695",
        "auth": "Mikrofilme aufgenommen von Manuskripten im Historischen Archiv der Stadt Wetzlar.",
        "publ": "FamilySearch; Film 1599707; Aufnahmengruppen-Nummer (DGS) 102779702",
        "repo": "REPO2",
    },
    "S6": {
        "titl": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1695-1718",
        "abbr": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1695-1718",
        "auth": "Mikrofilme aufgenommen von Manuskripten im Historischen Archiv der Stadt Wetzlar.",
        "publ": "FamilySearch; Film 1599708; Aufnahmengruppen-Nummer (DGS) 102779703",
        "repo": "REPO2",
    },
    "S7": {
        "titl": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1718-1734",
        "abbr": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1718-1734",
        "auth": "Mikrofilme aufgenommen von Manuskripten im Historischen Archiv der Stadt Wetzlar.",
        "publ": "FamilySearch; Film 1599835; Aufnahmengruppen-Nummer (DGS) 102779704",
        "repo": "REPO2",
    },
    "S8": {
        "titl": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1735-1746",
        "abbr": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1735-1746",
        "auth": "Mikrofilme aufgenommen von Manuskripten im Historischen Archiv der Stadt Wetzlar.",
        "publ": "FamilySearch; Film 1599836; Aufnahmengruppen-Nummer (DGS) 102779705",
        "repo": "REPO2",
    },
    "S9": {
        "titl": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1746-1761",
        "abbr": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1746-1761",
        "auth": "Mikrofilme aufgenommen von Manuskripten im Historischen Archiv der Stadt Wetzlar.",
        "publ": "FamilySearch; Film 1599836; Aufnahmengruppen-Nummer (DGS) 102779706",
        "repo": "REPO2",
    },
    "S10": {
        "titl": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1761-1780",
        "abbr": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1761-1780",
        "auth": "Mikrofilme aufgenommen von Manuskripten im Historischen Archiv der Stadt Wetzlar.",
        "publ": "FamilySearch; Film 1599838; Aufnahmengruppen-Nummer (DGS) 102779707",
        "repo": "REPO2",
    },
    "S11": {
        "titl": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1780-1798",
        "abbr": "Wetzlar Kirchenbuchkartei Gb Hb Sb 1780-1798",
        "auth": "Mikrofilme aufgenommen von Manuskripten im Historischen Archiv der Stadt Wetzlar.",
        "publ": "FamilySearch; Film 1599945; Aufnahmengruppen-Nummer (DGS) 102779708",
        "repo": "REPO2",
    },
    "S12": {
        "titl": "Wetzlar Kirchenbuch Geburten/Taufen 1571-1613 lutherisch",
        "abbr": "Wetzlar KbGb 1571-1613 lutherisch",
        "auth": "Evangelische Kirchengemeinde",
        "repo": "REPO3",
        "caln": "408/1",
        "text": "Kompletter Kirchenbuchbestand auch auf Mikrofiches vorhanden!",
    },
    "S13": {
        "titl": "Wetzlar Kirchenbuch Heiraten 1564-1590 lutherisch",
        "abbr": "Wetzlar KbHb 1564-1590 lutherisch",
        "auth": "Evangelische Kirchengemeinde",
        "repo": "REPO3",
        "caln": "408/1",
        "text": "Kompletter Kirchenbuchbestand auch auf Mikrofiches vorhanden!",
    },
    "S15": {
        "titl": "Wetzlar Kirchenbuch Geburten 1614-1687 lutherisch",
        "abbr": "Wetzlar KbGb 1614-1687 lutherisch",
        "auth": "Evangelische Kirchengemeinde",
        "repo": "REPO3",
        "caln": "408/2",
        "text": "Kompletter Kirchenbuchbestand auch auf Mikrofiches vorhanden!",
    },
    "S36": {
        "titl": "Wetzlar Kirchenbuch Sterbefälle 1613-1693 lutherisch",
        "abbr": "Wetzlar KbSb 1613-1693 lutherisch",
        "auth": "Evangelische Kirchengemeinde",
        "repo": "REPO3",
        "caln": "408/20",
        "text": "Kompletter Kirchenbuchbestand auch auf Mikrofiches vorhanden!",
    },
}

# Mapping von langen Quellnamen zu Source-IDs (wie in gw.py)
SOURCE_NAME_TO_ID = {
    "Wetzlar Kirchenbuchkartei Gb Hb Sb 1798-1831 Gb Hb Sb 1613-1798 (unsortiert) Ortsregister (nach Hauptstädten) Gb, Hb, Sb 1564-1831": "S1",
    "Wetzlar Kirchenbuchkartei Gb Hb Sb 1564-1611": "S2",
    "Wetzlar Kirchenbuchkartei Gb Hb Sb 1611-1632": "S3",
    "Wetzlar Kirchenbuchkartei Gb Hb Sb 1633-1670": "S4",
    "Wetzlar Kirchenbuchkartei Gb Hb Sb 1671-1695": "S5",
    "Wetzlar Kirchenbuchkartei Gb Hb Sb 1695-1718": "S6",
    "Wetzlar Kirchenbuchkartei Gb Hb Sb 1718-1734": "S7",
    "Wetzlar Kirchenbuchkartei Gb Hb Sb 1735-1746": "S8",
    "Wetzlar Kirchenbuchkartei Gb Hb Sb 1746-1761": "S9",
    "Wetzlar Kirchenbuchkartei Gb Hb Sb 1761-1780": "S10",
    "Wetzlar Kirchenbuchkartei Gb Hb Sb 1780-1798": "S11",
    "WETZLAR KbGb 1571-1613 lutherisch": "S12",
    "Wetzlar KbHb 1564-1590 lutherisch": "S13",
    "WETZLAR KbGb 1614-1687 lutherisch": "S15",
    "Wetzlar KbSb 1613-1693 lutherisch": "S36",
}
